spring:
  application:
    name:
      practice

#  batch:
#    job:
#      enabled: false

#  sql:
#   init:
#     mode: always
#     schema-locations: classpath:org/springframework/batch/core/schema-drop-h2.sql
  batch:
    jdbc:
      initialize-schema: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: root
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

# SQL 로깅 설정
#logging:
#  level:
#    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: TRACE